[package]
name = "epic_wallet_libwallet"
version = "3.2.2-1"
authors = ["Epic Developers <mimblewimble@lists.launchpad.net>"]
description = "Simple, private and scalable cryptocurrency implementation based on the MimbleWimble chain format."
license = "Apache-2.0"
repository = "https://github.com/mimblewimble/epic-wallet"
keywords = [ "crypto", "epic", "mimblewimble" ]
exclude = ["**/*.epic", "**/*.epic2"]
#build = "src/build/build.rs"
edition = "2018"

[dependencies]
blake2-rfc = "0.2"
failure = "0.1"
failure_derive = "0.1"
rand = "0.5"
serde = "1"
serde_derive = "1"
serde_json = "1"
log = "0.4"
uuid = { version = "0.7", features = ["serde", "v4"] }
chrono = { version = "0.4.4", features = ["serde"] }
lazy_static = "1"
strum = "0.15"
strum_macros = "0.15"
ed25519-dalek = "=1.0.0-pre.1"
sha3 = "0.8"
byteorder = "1"
data-encoding = "2"

epic_wallet_util = { path = "../util", version = "3.2.2-1" }
epic_wallet_config = { path = "../config", version = "3.0.0" }
